# Generated by Django 4.1.3 on 2023-01-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bill',
        ),
    ]
