# Generated by Django 4.1.3 on 2023-01-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_faculty_alter_transaction_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='full_marks',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_semester', to='Account.faculty'),
            preserve_default=False,
        ),
    ]
