# Generated by Django 4.1.3 on 2022-12-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fees',
        ),
    ]
