# Generated by Django 4.1.3 on 2023-01-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_transaction_unique_together_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='batch',
        ),
    ]
