# Generated by Django 4.1.3 on 2023-01-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_fee_admissionfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='admissionFee',
        ),
    ]
