# Generated by Django 4.1.3 on 2023-01-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_subject_full_marks_subject_pass_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
