# Generated by Django 4.1.3 on 2023-01-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
