# Generated by Django 4.1.3 on 2023-01-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.TextField(),
        ),
    ]
