# Generated by Django 4.1.3 on 2023-01-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_imagemodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
