# Generated by Django 4.1.3 on 2023-02-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_alter_transaction_user_alter_user_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middleName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
