# Generated by Django 4.1.3 on 2023-02-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_user_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
