# Generated by Django 4.1.3 on 2023-02-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_alter_user_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='faculty_mark', to='Account.faculty'),
            preserve_default=False,
        ),
    ]
