# Generated by Django 4.1.3 on 2023-03-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_alter_transaction_amount_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
