# Generated by Django 4.1.3 on 2023-03-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_alter_user_firstname_alter_user_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
