# Generated by Django 4.1.3 on 2023-03-13 08:34

import Account.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0023_alter_user_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, validators=[Account.validation.validate_password]),
        ),
    ]
