# Generated by Django 4.1.3 on 2023-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0024_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
