# Generated by Django 4.1.3 on 2023-03-14 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 14)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 14)),
        ),
    ]
