# Generated by Django 4.1.3 on 2022-12-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('uniqueRoll', models.CharField(max_length=30)),
                ('batch', models.IntegerField()),
                ('fees', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='student',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
