# Generated by Django 4.1.3 on 2022-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_studentdetail_remove_studentdetails_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='image',
            field=models.ImageField(upload_to='uploads/images'),
        ),
    ]
