# Generated by Django 4.1.3 on 2022-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_studentdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='phoneNumber',
            field=models.CharField(max_length=100),
        ),
    ]
