# Generated by Django 4.1.3 on 2022-12-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_user_delete_studentdetail_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
